### PR TITLE
doc(README): add Rajakvk as a contributor

### PR DESCRIPTION
**Pull request by rajakvk**
Fixes # NA
Screenshot: (if applicable):  
Description of the change: Updated contributors name (self) in README.md
First PR

### CODE REVIEW

**Review by souvikbasu — CHANGES_REQUESTED** [review]
please set the commit message as 
doc(README): add Rajakvk as a contributor

**Review by souvikbasu — CHANGES_REQUESTED** [review]
use present tense verbs like add instead of Updating in commit message. All small case

**Comment by rajakvk** [comment]
Set commit message as 
doc(README): add Rajakvk as a contributor
Please review.

**Review by souvikbasu — CHANGES_REQUESTED** [review]
create a single commit instead of 3 commits for a PR.
Also do not keep any merge commits. use `--rebase`  key during `git pull` command to avoid creating Merge commits

**Comment by rajakvk** [comment]
Removed other commits. Now PR has only one commit. Please review.

**Review by souvikbasu — CHANGES_REQUESTED** [review]
Commit message is: docs: rEADME.md update
Change it to: docs(README.md): add Rajakvk as a contributor
You can check the format of the commit messages in the README file

**Review by souvikbasu — APPROVED** [review]

**Pull request merged**
